### ISSUE TITLE
specify license for toki

### ISSUE THREAD

**Issue by ywwg** [taylorchu/toki#2]
Hello @taylorchu 

First of all thank you for making this project. It's been one of our dependencies for [carbon-relay-ng](https://github.com/grafana/carbon-relay-ng/blob/master/go.mod#L29) for quite some time and we've never had any issues with it!

We just found out that this project has no license file, and by default, unlicensed code is considered "all rights reserved" and not open source. We were wondering if you'd mind adding a license you consider appropriate for it so that we can continue to use the project. If that's not something you want to do, we can find an alternative solution. Please let us know when you have a moment and thank you again.

**Comment by npazosmendez** [comment]
Hello @taylorchu! Just checking in to see if you had a chance to look at this

**Comment by taylorchu** [comment]
I will upload the MIT license today

**Comment by taylorchu** [comment]
This is done

**Comment by npazosmendez** [comment]
Thank you, much appreciated!
